package com.parentabc.entity;
// Generated Oct 19, 2016 1:56:34 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Answer generated by hbm2java
 */
public class Answer implements java.io.Serializable {

    private static final long serialVersionUID = 5384087339603614147L;

    private int id;
    private int version;
    private String acontent;
    private int creatorId;
    private MemberUser memberUser;
    private int QId;
    private Question question;
    private Date createDate;
    private Date updateDate;
    private boolean best;
    private int points;
    private int status;
    private int type;

    public Answer() {
    }

    public Answer(int id) {
        this.id = id;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public MemberUser getMemberUser() {
        return memberUser;
    }

    public void setMemberUser(MemberUser memberUser) {
        this.memberUser = memberUser;
    }

    public Question getQuestion() {
        return question;
    }

    public void setQuestion(Question question) {
        this.question = question;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getAcontent() {
        return this.acontent;
    }

    public void setAcontent(String acontent) {
        this.acontent = acontent;
    }

    public int getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(int creatorId) {
        this.creatorId = creatorId;
    }

    public int getQId() {
        return this.QId;
    }

    public void setQId(int QId) {
        this.QId = QId;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public boolean getBest() {
        return this.best;
    }

    public void setBest(boolean best) {
        this.best = best;
    }

    public int getPoints() {
        return this.points;
    }

    public void setPoints(int points) {
        this.points = points;
    }

    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getType() {
        return this.type;
    }

    public void setType(int type) {
        this.type = type;
    }

}
