package com.parentabc.entity;
// Generated Oct 19, 2016 1:56:34 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.List;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

    private static final long serialVersionUID = -6234425377671006740L;

    private int id;
    private int version;
    @NotNull(message = "请输入问题标题")
    @Min(value = 1, message = "问题标题不对")
    private String qtitle;
    @NotNull(message = "请输入问题详细描述")
    @Min(value = 1, message = "请输入问题详细描述")
    private String qcontent;
    private Date createDate;
    private int creatorId;
    private MemberUser memberUser;
    private Date updateDate;
    private int points;
    private int type = 1;// 1:普通问题, 2:向管理者提的问题,
    private int status = 1; //1:已发布的问题, 2:禁止发布问题 ,7:草稿问题, 9:已删除问题
    private int views;
    private int nickname;
    private int age;
    private String sex; //0:女 1:男
    private int answersSize;
    private List<Answer> answers;

    public Question() {
    }

    public Question(int id, String qcontent, int creatorId) {
        this.id = id;
        this.qcontent = qcontent;
        this.creatorId = creatorId;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getNickname() {
        return nickname;
    }

    public void setNickname(int nickname) {
        this.nickname = nickname;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getQtitle() {
        return qtitle;
    }

    public int getAnswersSize() {
        return answersSize;
    }

    public void setAnswersSize(int answersSize) {
        this.answersSize = answersSize;
    }

    public void setQtitle(String qtitle) {
        this.qtitle = qtitle;
    }

    public MemberUser getMemberUser() {
        return memberUser;
    }

    public void setMemberUser(MemberUser memberUser) {
        this.memberUser = memberUser;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getQcontent() {
        return this.qcontent;
    }

    public void setQcontent(String qcontent) {
        this.qcontent = qcontent;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public int getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(int creatorId) {
        this.creatorId = creatorId;
    }

    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public int getPoints() {
        return this.points;
    }

    public void setPoints(int points) {
        this.points = points;
    }

    public int getType() {
        return this.type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getViews() {
        return this.views;
    }

    public void setViews(int views) {
        this.views = views;
    }

    public List<Answer> getAnswers() {
        return answers;
    }

    public void setAnswers(List<Answer> answers) {
        this.answers = answers;
    }

}
